### ISSUE TITLE
How to create simple dialog to show user

### ISSUE THREAD

**Issue by eybisi** [jadx-decompiler/jadx-example-plugin#5]
Let's say I've collected some information from the current apk file. After that I would like to show to the user that information, for example [a comment dialog](https://github.com/skylot/jadx/blob/master/jadx-gui/src/main/java/jadx/gui/ui/dialog/CommentDialog.java). This dialog can be shown after pressing some button in menu bar which is added with [addMenuAction](https://github.com/skylot/jadx/blob/b5e3dcf70fb388c46e27c2acd3411e7bc52eb2d4/jadx-core/src/main/java/jadx/api/plugins/gui/JadxGuiContext.java#L22).

 I've tried to find an access to mainWindow from [JadxGuiContext](https://github.com/skylot/jadx/blob/b5e3dcf70fb388c46e27c2acd3411e7bc52eb2d4/jadx-core/src/main/java/jadx/api/plugins/gui/JadxGuiContext.java#L12) with no success. I don't know how to use [uiRun](https://github.com/skylot/jadx/blob/b5e3dcf70fb388c46e27c2acd3411e7bc52eb2d4/jadx-core/src/main/java/jadx/api/plugins/gui/JadxGuiContext.java#L17) function to achieve this. If you can add some examples for this case, it will be very helpful for future plugins.

**Comment by eybisi** [comment]
well, thx to chatgpt I can get current window like this:
```
    public void showJadxDialogWithoutFrameAccess() {
        // Use uiRun to create the dialog on the Event Dispatch Thread
        uiRun(() -> {
            // Retrieve the currently focused window (likely the main Jadx window)
            Window currentWindow = KeyboardFocusManager.getCurrentKeyboardFocusManager().getActiveWindow();
            
            if (currentWindow instanceof Frame) {
                // If the active window is a Frame, show the dialog
                SimpleDialog.showDialog((Frame) currentWindow, "Jadx Dialog", "Hello from Jadx plugin!");
            } else {
                // If the current window is not a Frame (or not available), handle gracefully
                System.out.println("No active Frame available to attach the dialog to.");
            }
        });
    }
```

**Comment by skylot** [comment]
@eybisi I think you want to do something like this:
```java
guiContext.addMenuAction("Example dialog window", () -> {
	JDialog d = new JDialog();
	d.setTitle("Dialog box");
	JLabel label = new JLabel("This is a dialog box");
	d.add(label);
	d.setSize(200, 100);
	d.setVisible(true);
});
```

Although, I agree, there is no way to get main window to use is as an owner argument in `JDialog` constructor. I will add such method to API.

**Comment by skylot** [comment]
> I will add such method to API.

Done, use [getMainFrame()](https://github.com/skylot/jadx/commit/90185fd947402a9110df4053073468f3759076c9#diff-a1e4b6105587213638df588cf9c27101b577205361318670f8467ed41fd6c308R58) with `1.5.1-SNAPSHOT`.
